CREATE TABLE [dbo].[Clients]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[CUIL] VARCHAR(11) NOT NULL,
	[PhoneNumber] NVARCHAR(50) NOT NULL,
)
